apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: projeto-backend
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: adrjsilva/projeto-backend:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80