apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
  namespace: projeto-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dados
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql-dados/"