machines = {
  "node01" => {"memory" => "1024", "cpu" => "1", "image" => "bento/ubuntu-22.04", "ip" => "10.0.0.101"},
  "node02" => {"memory" => "1024", "cpu" => "1", "image" => "bento/ubuntu-22.04", "ip" => "10.0.0.102"},
  "node03" => {"memory" => "1024", "cpu" => "1", "image" => "bento/ubuntu-22.04", "ip" => "10.0.0.103"}
}


Vagrant.configure(2) do |config|
    config.vm.define "master" do |master|
      master.vm.box = "bento/ubuntu-22.04"
      master.vm.hostname = "master"
      master.vm.network "private_network", ip:"10.0.0.100"
      master.vm.provider "virtualbox" do |vb|
        vb.name = "master"
        vb.memory = "1024"
        vb.cpus = "1"
      end
      master.vm.provision "shell", path: "scripts/instalar-docker.sh"
      master.vm.provision "shell", path: "scripts/instalar-swarm.sh"
    end  
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip:"#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
      end
      machine.vm.provision "shell", path: "scripts/instalar-docker.sh"
      machine.vm.provision "shell", path: "scripts/ingressar-cluster-swarm.sh"
    end
  end  
end


 